# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  basket.api:
    build:
      context: "/home/faahiero/Documentos/Workspace/dotnet/AspNetMicroservices/src"
      dockerfile: "Services/Basket/Basket.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "/riderDebugger/linux-x64/dotnet/dotnet"
    - "/riderDebugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "/home/faahiero/.nuget/packages"
      NUGET_FALLBACK_PACKAGES: "/home/faahiero/.nuget/packages"
      RIDER_DEBUGGER_LOG_DIR: "/riderLogs"
      RESHARPER_LOG_CONF: "/riderLogsConf/backend-log.xml"
    image: "basketapi:dev"
    ports:
    - "127.0.0.1:57008:57100"
    - "127.0.0.1:57208:57300"
    volumes:
    - "/home/faahiero/.nuget/packages:/root/.nuget/fallbackpackages"
    - "/home/faahiero/Documentos/Workspace/dotnet/AspNetMicroservices/src/Services/Basket/Basket.API:/app:rw"
    - "/home/faahiero/Documentos/Workspace/dotnet/AspNetMicroservices/src:/src:rw"
    - "/home/faahiero/.local/share/JetBrains/RiderRemoteDebugger/2023.2.3/Linux64:/riderDebugger"
    - "/home/faahiero/.local/share/JetBrains/Toolbox/apps/rider/bin:/riderLogsConf"
    - "/home/faahiero/.cache/JetBrains/Rider2023.2/log/DebuggerWorker/JetBrains.Debugger.Worker.2023_11_21_14_52_42:/riderLogs:rw"
    working_dir: "/app"
  catalog.api:
    build:
      context: "/home/faahiero/Documentos/Workspace/dotnet/AspNetMicroservices/src"
      dockerfile: "Services/Catalog/Catalog.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "/riderDebugger/linux-x64/dotnet/dotnet"
    - "/riderDebugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "/home/faahiero/.nuget/packages"
      NUGET_FALLBACK_PACKAGES: "/home/faahiero/.nuget/packages"
      RIDER_DEBUGGER_LOG_DIR: "/riderLogs"
      RESHARPER_LOG_CONF: "/riderLogsConf/backend-log.xml"
    image: "catalogapi:dev"
    ports:
    - "127.0.0.1:57009:57100"
    - "127.0.0.1:57209:57300"
    volumes:
    - "/home/faahiero/.nuget/packages:/root/.nuget/fallbackpackages"
    - "/home/faahiero/Documentos/Workspace/dotnet/AspNetMicroservices/src/Services/Catalog/Catalog.API:/app:rw"
    - "/home/faahiero/Documentos/Workspace/dotnet/AspNetMicroservices/src:/src:rw"
    - "/home/faahiero/.local/share/JetBrains/RiderRemoteDebugger/2023.2.3/Linux64:/riderDebugger"
    - "/home/faahiero/.local/share/JetBrains/Toolbox/apps/rider/bin:/riderLogsConf"
    - "/home/faahiero/.cache/JetBrains/Rider2023.2/log/DebuggerWorker/JetBrains.Debugger.Worker.2023_11_21_14_52_42:/riderLogs:rw"
    working_dir: "/app"
  discount.api:
    build:
      context: "/home/faahiero/Documentos/Workspace/dotnet/AspNetMicroservices/src"
      dockerfile: "Services/Discount/Discount.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "/riderDebugger/linux-x64/dotnet/dotnet"
    - "/riderDebugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "/home/faahiero/.nuget/packages"
      NUGET_FALLBACK_PACKAGES: "/home/faahiero/.nuget/packages"
      RIDER_DEBUGGER_LOG_DIR: "/riderLogs"
      RESHARPER_LOG_CONF: "/riderLogsConf/backend-log.xml"
    image: "discountapi:dev"
    ports:
    - "127.0.0.1:57010:57100"
    - "127.0.0.1:57210:57300"
    volumes:
    - "/home/faahiero/.nuget/packages:/root/.nuget/fallbackpackages"
    - "/home/faahiero/Documentos/Workspace/dotnet/AspNetMicroservices/src/Services/Discount/Discount.API:/app:rw"
    - "/home/faahiero/Documentos/Workspace/dotnet/AspNetMicroservices/src:/src:rw"
    - "/home/faahiero/.local/share/JetBrains/RiderRemoteDebugger/2023.2.3/Linux64:/riderDebugger"
    - "/home/faahiero/.local/share/JetBrains/Toolbox/apps/rider/bin:/riderLogsConf"
    - "/home/faahiero/.cache/JetBrains/Rider2023.2/log/DebuggerWorker/JetBrains.Debugger.Worker.2023_11_21_14_52_42:/riderLogs:rw"
    working_dir: "/app"
  discount.grpc:
    build:
      context: "/home/faahiero/Documentos/Workspace/dotnet/AspNetMicroservices/src"
      dockerfile: "Services/Discount/Discount.GRPC/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "/riderDebugger/linux-x64/dotnet/dotnet"
    - "/riderDebugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "/home/faahiero/.nuget/packages"
      NUGET_FALLBACK_PACKAGES: "/home/faahiero/.nuget/packages"
      RIDER_DEBUGGER_LOG_DIR: "/riderLogs"
      RESHARPER_LOG_CONF: "/riderLogsConf/backend-log.xml"
    image: "discountgrpc:dev"
    ports:
    - "127.0.0.1:57011:57100"
    - "127.0.0.1:57211:57300"
    volumes:
    - "/home/faahiero/.nuget/packages:/root/.nuget/fallbackpackages"
    - "/home/faahiero/Documentos/Workspace/dotnet/AspNetMicroservices/src/Services/Discount/Discount.GRPC:/app:rw"
    - "/home/faahiero/Documentos/Workspace/dotnet/AspNetMicroservices/src:/src:rw"
    - "/home/faahiero/.local/share/JetBrains/RiderRemoteDebugger/2023.2.3/Linux64:/riderDebugger"
    - "/home/faahiero/.local/share/JetBrains/Toolbox/apps/rider/bin:/riderLogsConf"
    - "/home/faahiero/.cache/JetBrains/Rider2023.2/log/DebuggerWorker/JetBrains.Debugger.Worker.2023_11_21_14_52_42:/riderLogs:rw"
    working_dir: "/app"
  ocelot.api:
    build:
      context: "/home/faahiero/Documentos/Workspace/dotnet/AspNetMicroservices/src"
      dockerfile: "ApiGateways/OcelotApiGw/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "/riderDebugger/linux-x64/dotnet/dotnet"
    - "/riderDebugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "/home/faahiero/.nuget/packages"
      NUGET_FALLBACK_PACKAGES: "/home/faahiero/.nuget/packages"
      RIDER_DEBUGGER_LOG_DIR: "/riderLogs"
      RESHARPER_LOG_CONF: "/riderLogsConf/backend-log.xml"
    image: "ocelotapi:dev"
    ports:
    - "127.0.0.1:57012:57100"
    - "127.0.0.1:57212:57300"
    volumes:
    - "/home/faahiero/.nuget/packages:/root/.nuget/fallbackpackages"
    - "/home/faahiero/Documentos/Workspace/dotnet/AspNetMicroservices/src/ApiGateways/OcelotApiGw:/app:rw"
    - "/home/faahiero/Documentos/Workspace/dotnet/AspNetMicroservices/src:/src:rw"
    - "/home/faahiero/.local/share/JetBrains/RiderRemoteDebugger/2023.2.3/Linux64:/riderDebugger"
    - "/home/faahiero/.local/share/JetBrains/Toolbox/apps/rider/bin:/riderLogsConf"
    - "/home/faahiero/.cache/JetBrains/Rider2023.2/log/DebuggerWorker/JetBrains.Debugger.Worker.2023_11_21_14_52_42:/riderLogs:rw"
    working_dir: "/app"
  order.api:
    build:
      context: "/home/faahiero/Documentos/Workspace/dotnet/AspNetMicroservices/src"
      dockerfile: "Services/Ordering/Ordering.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "/riderDebugger/linux-x64/dotnet/dotnet"
    - "/riderDebugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "/home/faahiero/.nuget/packages"
      NUGET_FALLBACK_PACKAGES: "/home/faahiero/.nuget/packages"
      RIDER_DEBUGGER_LOG_DIR: "/riderLogs"
      RESHARPER_LOG_CONF: "/riderLogsConf/backend-log.xml"
    image: "orderapi:dev"
    ports:
    - "127.0.0.1:57013:57100"
    - "127.0.0.1:57213:57300"
    volumes:
    - "/home/faahiero/.nuget/packages:/root/.nuget/fallbackpackages"
    - "/home/faahiero/Documentos/Workspace/dotnet/AspNetMicroservices/src/Services/Ordering/Ordering.API:/app:rw"
    - "/home/faahiero/Documentos/Workspace/dotnet/AspNetMicroservices/src:/src:rw"
    - "/home/faahiero/.local/share/JetBrains/RiderRemoteDebugger/2023.2.3/Linux64:/riderDebugger"
    - "/home/faahiero/.local/share/JetBrains/Toolbox/apps/rider/bin:/riderLogsConf"
    - "/home/faahiero/.cache/JetBrains/Rider2023.2/log/DebuggerWorker/JetBrains.Debugger.Worker.2023_11_21_14_52_42:/riderLogs:rw"
    working_dir: "/app"
  shopping.aggregator:
    build:
      context: "/home/faahiero/Documentos/Workspace/dotnet/AspNetMicroservices/src"
      dockerfile: "ApiGateways/Shopping.Aggregator/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "/riderDebugger/linux-x64/dotnet/dotnet"
    - "/riderDebugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "/home/faahiero/.nuget/packages"
      NUGET_FALLBACK_PACKAGES: "/home/faahiero/.nuget/packages"
      RIDER_DEBUGGER_LOG_DIR: "/riderLogs"
      RESHARPER_LOG_CONF: "/riderLogsConf/backend-log.xml"
    image: "shoppingaggregator:dev"
    ports:
    - "127.0.0.1:57014:57100"
    - "127.0.0.1:57214:57300"
    volumes:
    - "/home/faahiero/.nuget/packages:/root/.nuget/fallbackpackages"
    - "/home/faahiero/Documentos/Workspace/dotnet/AspNetMicroservices/src/ApiGateways/Shopping.Aggregator:/app:rw"
    - "/home/faahiero/Documentos/Workspace/dotnet/AspNetMicroservices/src:/src:rw"
    - "/home/faahiero/.local/share/JetBrains/RiderRemoteDebugger/2023.2.3/Linux64:/riderDebugger"
    - "/home/faahiero/.local/share/JetBrains/Toolbox/apps/rider/bin:/riderLogsConf"
    - "/home/faahiero/.cache/JetBrains/Rider2023.2/log/DebuggerWorker/JetBrains.Debugger.Worker.2023_11_21_14_52_42:/riderLogs:rw"
    working_dir: "/app"
  shopping.web:
    build:
      context: "/home/faahiero/Documentos/Workspace/dotnet/AspNetMicroservices/src"
      dockerfile: "WebApps/ShoppingWebApp/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "/riderDebugger/linux-x64/dotnet/dotnet"
    - "/riderDebugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    environment:
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net7.0/ShoppingWebApp.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "/home/faahiero/.nuget/packages"
      NUGET_FALLBACK_PACKAGES: "/home/faahiero/.nuget/packages"
      RIDER_DEBUGGER_LOG_DIR: "/riderLogs"
      RESHARPER_LOG_CONF: "/riderLogsConf/backend-log.xml"
    image: "shoppingweb:dev"
    ports:
    - "127.0.0.1:57015:57100"
    - "127.0.0.1:57215:57300"
    volumes:
    - "/home/faahiero/.nuget/packages:/root/.nuget/fallbackpackages"
    - "/home/faahiero/Documentos/Workspace/dotnet/AspNetMicroservices/src/WebApps/ShoppingWebApp:/app:rw"
    - "/home/faahiero/Documentos/Workspace/dotnet/AspNetMicroservices/src:/src:rw"
    - "/home/faahiero/.local/share/JetBrains/RiderRemoteDebugger/2023.2.3/Linux64:/riderDebugger"
    - "/home/faahiero/.local/share/JetBrains/Toolbox/apps/rider/bin:/riderLogsConf"
    - "/home/faahiero/.cache/JetBrains/Rider2023.2/log/DebuggerWorker/JetBrains.Debugger.Worker.2023_11_21_14_52_42:/riderLogs:rw"
    working_dir: "/app"
